### ISSUE TITLE
期待出 linux

### ISSUE THREAD

**Issue by ayuayue** [clouDr-f2e/rubick#18]

**Comment by As-XiongShijie** [comment]
期待出 linux

**Comment by As-XiongShijie** [comment]
就很酷~

**Comment by As-XiongShijie** [comment]
我在ubuntu21.04安装，提示这个：
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/snap/rubick2/x1/resources/app.asar/node_modules/iohook/index.js:24:21)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
`

**Comment by SOVLOOKUP** [comment]
> 我在ubuntu21.04安装，提示这个：
> `A JavaScript error occurred in the main process Uncaught Exception: Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846) at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18) at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073) at Module.load (internal/modules/cjs/loader.js:935:32) at Module._load (internal/modules/cjs/loader.js:776:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12913) at Module.require (internal/modules/cjs/loader.js:959:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/snap/rubick2/x1/resources/app.asar/node_modules/iohook/index.js:24:21) at Module._compile (internal/modules/cjs/loader.js:1078:30) `

试试这个，Ubuntu 下貌似这个依赖不会被系统自带
```
sudo apt-get install -y libxkbcommon-x11-0
```

**Comment by As-XiongShijie** [comment]
系统自带的有，'(libxkbcommon-x11-0 已经是最新版 (1.0.3-2))'
建议检查一下 package.json

**Comment by As-XiongShijie** [comment]
> > 我在ubuntu21.04安装，提示这个： 
> > `A JavaScript error occurred in the main process Uncaught Exception: Error: libxkbcommon-x11.so.0: cannot open shared object file: No such file or directory at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846) at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18) at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073) at Module.load (internal/modules/cjs/loader.js:935:32) at Module._load (internal/modules/cjs/loader.js:776:14) at Function.f._load (electron/js2c/asar_bundle.js:5:12913) at Module.require (internal/modules/cjs/loader.js:959:19) at require (internal/modules/cjs/helpers.js:88:18) at Object.<anonymous> (/snap/rubick2/x1/resources/app.asar/node_modules/iohook/index.js:24:21) at Module._compile (internal/modules/cjs/loader.js:1078:30) `
> 
> 试试这个，Ubuntu 下貌似这个依赖不会被系统自带
> 
> ```
> sudo apt-get install -y libxkbcommon-x11-0
> ```

系统自带的有，'(libxkbcommon-x11-0 已经是最新版 (1.0.3-2))'
建议检查一下 package.json

**Comment by SOVLOOKUP** [comment]
@As-XiongShijie 你的 Ubuntu 是在 WSL 中运行的吗？现在 iohook 不能在WSL中工作： https://github.com/wilix-team/iohook/issues/249

如果是本机运行的话，麻烦再另开一个 BUG issue ，我们会将其加入迭代计划

**Comment by As-XiongShijie** [comment]
> @As-XiongShijie 你的 Ubuntu 是在 WSL 中运行的吗？现在 iohook 依赖不能在WSL中工作： [wilix-team/iohook#249](https://github.com/wilix-team/iohook/issues/249)
> 
> 如果是本机运行的话，麻烦再另开一个 BUG issue ，我们会将其加入迭代计划

是在物理机上运行的，我去开个BUG issue
