### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by gclm** [clouDr-f2e/rubick#25]
## 环境：
- mac : 11.5.1
- node ：v14.16.0
## 报错
```
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path /Users/gclm/Projects/03-personal/rubick/node_modules/lzma-native
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.16.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/Users/gclm/opt/anaconda3/bin/python3"
npm ERR! gyp info spawn /Users/gclm/opt/anaconda3/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/gclm/Projects/03-personal/rubick/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/gclm/Projects/03-personal/rubick/node_modules/lzma-native/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/gclm/Projects/03-personal/rubick/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/gclm/Library/Caches/node-gyp/14.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/gclm/Library/Caches/node-gyp/14.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/gclm/Projects/03-personal/rubick/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/gclm/Library/Caches/node-gyp/14.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/gclm/Projects/03-personal/rubick/node_modules/lzma-native',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: Undefined variable module_path in binding.gyp while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/gclm/Projects/03-personal/rubick/node_modules/node-gyp/lib/configure.js:351:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/Users/gclm/.nvm/versions/node/v14.16.0/bin/node" "/Users/gclm/Projects/03-personal/rubick/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/gclm/Projects/03-personal/rubick/node_modules/lzma-native
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gclm/.npm/_logs/2021-08-11T01_12_08_027Z-debug.log

```

**Comment by mucpsing** [comment]
最后解决了吗

**Comment by gclm** [comment]
没。前端菜鸡

**Comment by muwoo** [comment]
@gclm 尝试一下 `cnpm install`

**Comment by gclm** [comment]
cnpm 确实没问题，但是打包的时候有问题。
